/' Arquivo com diagrama de classe principal do projeto.
Para visualizar o diagrama instale o plugin do eclipse, ver instrucões em: http://plantuml.com/eclipse '/
   
@startuml
page 2x2
skinparam defaultFontName Trebuchet MS
skinparam ClassBackgroundColor<<View>> LightCyan
skinparam ClassBackgroundColor<<Embeddable>> WhiteSmoke
skinparam nodesep 10
skinparam ranksep 10
/'left to right direction'/

package "br.jus.tre_pa.app.scoop2019.domain" <<Frame>> {

  	class ZonaEleitoral {
		- codObjeto: String[255] {id}
        - numero: String[255]
	}
	
		class Localidade {
		- codObjeto: String[255] {id}
        - nomLocalidade: String[255]
	}
        
        class LocalVotacao {
		- codObjeto: String[255] {id}
        - numLocal: String[255]
        - nomLocal: String[255]
	}
}

/' Relacionamentos entre entidades '/

ZonaEleitoral "1" <--> "0..*" LocalVotacao : zonaLV
Localidade "1" <--> "0..*" LocalVotacao : localidadeLV

@enduml
